# -*- coding: utf-8 -*-
"""SmasungAEDEstadoCuentas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E4ENVbupwkQ3Z64-SSnA58om0iJwIUex

# Análisis de datos de la empresa Samsung de los estados de cuentas del año 2018-2022

Librerias
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics
import scipy.stats
from empiricaldist import Pmf, Cdf
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats as ss

!pip install empiricaldist

"""Bases de datos"""

df= pd.read_csv("/content/SamsungCuentaResultados.csv")
df

"""¿Qué tipo de dato son las variables del conjunto de datos?"""

(
df
.dtypes
.value_counts()
)

"""¿Cuántas variables de cada tipo de dato tenemos en el conjunto de datos?"""

df.shape

"""¿Existen valores nulos explícitos en un conjunto de datos?

"""

(
df
.isnull()
.any()
)

"""De existir valores nulos ¿Cuántas tenemos por cada variable?"""

(
df
.isnull()
.sum()
)

"""¿Cuántos valores nulos tenemos en un total en el conjunto de datos?"""

(
df
.isnull()
.sum()
.sum()
)

"""¿Cuál es la proporción de valores nulos por cada variable?

"""

(
df
.isnull()
.transpose()
.pipe(
lambda FunctionName:(
sns.heatmap(
data= FunctionName
)
)
)
)

"""¿Cuántas observaciones perdemos si eliminamos los datos faltantes?"""

dfdep= (
df
.dropna()
)
dfdep

"""# CONTEOS Y PROPORCIONES"""

dfdep.describe(include= "all")

sns.catplot(
data=dfdep,
x="age_2022",
kind="count",
height=10,
aspect=2
)

"""MEDIDAS DE TENDENCIA CENTRAL"""

dfdep.mean

dfdep.median

dfdep.mode

"""MEDIDAS DE DISPERCION"""

dfdep.max()

dfdep.min()

"""¿Cuál es la desviación estándar de las variables?"""

dfdep.std

"""Rango intercuartilico"""

dfdep.quantile

fig, ax = plt.subplots(figsize = (30, 10))
sns.histplot(
data=dfdep,
x="age_2022",

)

"""# DISTRIBUCIONES: PMFs, CDFs,PDFs

PMFs
"""

fig, ax = plt.subplots(figsize = (30, 10))

sns.histplot(
data=dfdep,
x="age_2022",
binwidth=1,
stat="probability"
)

"""ECDFs"""

fig, ax = plt.subplots(figsize = (30, 10))
sns.ecdfplot(
data=dfdep,
x="age_2022",
)

"""Comparacion; año 2022 con el año 2018"""

fig, ax = plt.subplots(figsize = (30, 10))
sns.ecdfplot(
data=dfdep,
x="age_2022",
hue="age_2018",
)

"""FUNCION DE DENSIDAD DE
PROBABILIDAD
"""

fig, ax = plt.subplots(figsize = (30, 10))

sns.countplot(data=dfdep, x="age_2022")

plt.xlabel('Duración de exposición')
plt.ylabel('Densidad')
plt.title('Estimación de la Densidad de Kernel')
plt.grid(True)
plt.show()

"""ANALISIS BIVARIADO"""

fig, ax = plt.subplots(figsize = (30, 10))
sns.scatterplot(data=dfdep, x="age_2018", y="age_2022", alpha=1, s=40)

plt.xlabel('age_2018 (grados)')
plt.ylabel('age_2022 (grados)')
plt.title('Gráfico de Dispersión')
plt.grid(True)
plt.show()

"""MATRICES DE CORRELACION"""

dfdep.corr

"""ANALISIS
DE REGRESION SIMPLE
"""

fig, ax = plt.subplots(figsize = (30, 30))
sns.scatterplot(
data=dfdep,
x="age_2018",
y="age_2022",
)